### ISSUE TITLE
Package error?

### ISSUE THREAD

**Issue by OutRunner** [timetorock/laravel-monolog-sentry#1]
Hi,

I'm trying to install this package via composer but I'm getting this error:
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for timetorock/laravel-monolog-sentry ^1.6 -> satisfiable by timetorock/laravel-monolog-sentry[v1.6].
    - timetorock/laravel-monolog-sentry v1.6 requires sentry/sentry-laravel 0.10.1 -> satisfiable by sentry/sentry-laravel[0.10.1] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.`

The version of Sentry's packaged I'm using is 1.2.0, which is way ahead of 0.10.1. Am I doing something wrong or does something need to be updated?

**Comment by timetorock** [comment]
Hi, currently library do not support the new version of Sentry, as it was totally rewritten. Need to make update, but I'm can't make it in a nearest time.

**Comment by OutRunner** [comment]
Ah right, thanks for explaining. It’s always a pain when something like that completely changes! 🙂
